apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-v2-parameter
  namespace: ${parameters['namespace'] }
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-v2-parameter
    spec:
      containers:
      - name: k8s-v2-parameter
        image: nginx
        resources:
          requests:
            memory: "1M"
            cpu: "1m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
