apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-v2-example
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-v2-example
    spec:
      volumes:
      - name: k8-v2-config-map
        configMap:
          name: k8-v2-config-map
      containers:
      - name: k8s-v2-example
        image: nginx
        resources:
          requests:
            memory: "128M"
            cpu: "1000m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
