apiVersion: v1
kind: Pod
metadata:
  name: js-spinnaker-nginx
  namespace: default
  labels:
    foo: julio
spec:
  containers:
  - name: nginx
    image: nginx:1.13.8
    ports:
    - containerPort: 80
