---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-web-0
  labels:
    app: nginx
spec:
  capacity:
    storage: 1.0Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default/nginx/nginx-0
